[project]
name = "slurm-use-enforcer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "psutil>=7.0.0",
    "pydantic>=2.11.2",
    "slack-sdk>=3.35.0",
]
